### ISSUE TITLE
investigate using po4a for parsing Rd files

### ISSUE THREAD

**Issue by daroczig** [eliocamp/rhelpi18n#1]
Instead of writing something custom (and probably complex), maybe [po4a](https://po4a.org) might be extended with an `Rd` parser to be able to use the already implemented features for translating documentation as described at https://po4a.org/man/man7/po4a.7.php

Looking at the LaTeX parser might be a good starting point https://github.com/mquinson/po4a

**Comment by eliocamp** [comment]
Could be a good lead, since .Rd is kind of latex-y. 

I think the source is here: https://github.com/mquinson/po4a/blob/master/lib/Locale/Po4a/LaTeX.pm

I've never programmed in PERL, but this doesn't look terrible incomprehensible. Hopefully it could be adapting by declaring all the various tags. 


(BTW, R has it's own Rd parser (`tools::parse_Rd()`) but according to Deepayan, it's not very robust).

**Comment by eliocamp** [comment]
pkgdown has an .Rd parser that should work well enough. https://github.com/r-lib/pkgdown/blob/main/R/rd.R

**Comment by daroczig** [comment]
I don't think the actual Rd parsing is the most difficult task, and po4a provides much more features (not only extracting strings, but managing the whole flow).

**Comment by eliocamp** [comment]
Also check rd2list:

https://github.com/coolbutuseless/rd2list

**Comment by eliocamp** [comment]
After investigating and trying a couple of implementations, I think that the current formats already available in R through `tools::parse_Rd(rd_file)` and  `utils:::.getHelpFile(help("mean"))` work well enough.
