### ISSUE TITLE
An ideia to simplify the project ? Not sure

### ISSUE THREAD

**Issue by pedropark99** [eliocamp/rhelpi18n#4]
Your proposal is a very interesting idea, but it is definetely a hard one to implement. This is a problem similar to the hard problem of making a C or C++ library portable accross multiple platforms, or, to deal with different memory allocation strategies accross multiple operational systems.

I think that what makes your idea hard is to integrate it into R itself, or, into the workflow of developing R packages, meaning that, ways to make this idea like a normal step that every R developer could do inside their workflow.

I am not saying that this is not possible to be done; I am not saying that the step of translating the artifacts should not be a "developer's task", or, a normal step that every R developer could do inside their workflow. I am just saying that making these tasks very well integrated inside the system, and make them work well together.... this is the really hard part of this proposal.

So I am thinking, if this is hard to do, it could be a good idea to think into a MVP (minimal viable product). I think that the nice thing to do here, is to remove the idea of integrating your idea into R itself, or R `help()`, or into a R developer workflow like `devtools::build_vignette()`, etc..

If you look at the R package `{dados}` it is a package created to translate the R datasets used in R4DS to Portuguese. It as an external resource, outside of R and actually made some success.

So what if, you used this proposal to create a central repository of translated documentation. In other words, a website like [Rdocumentation](https://www.rdocumentation.org/), but filled with translated versions of the packages. To do that, we could implement a R package that does the following:

- collect the package Rd files or the Rmd files from CRAN, Github, whatever, parse it to get the text content, send it to an translation API or something, and save the translated content (which is faily similar to @maelle [babeldown](https://docs.ropensci.org/babeldown/) package, but for Rds instead of Rmds).
- then, having the Rd or Rmd files translated, it can convertit or compile it to HTML or PDF or whatever using the standard R tools (R CMD build).

We could start by translating a small sample, probably the most used R packages, to a small sample of languages, like Spanish and Portuguese. Then, we detect the points of improvement of the package and improve it. Then we expand it to other packages, with more languages.

The process of translating the Rd or Rmd files, and re-compiling it to HTML and PDF could be redone every time a new version of the package is pushed into CRAN.

I am not sure if this is really the best path to follow. These are just ideas that popped out in my mind and decided to write it down here.

Good idea and good proposal 😉

**Comment by eliocamp** [comment]
I might be misunderstanding your proposal but I don't think this system is that much simpler than the proposal. It also involves parsing .Rd files into a translatable format, translating it and then putting the .Rd files back together. 

I think that crafting a whole website to host the documentation might be even more complex (at least for me) than putting them into a package and integrate them into the usual R ecosystem. (Kind of like the [datos](https://cran.r-project.org/web/packages/datos/index.html) package)

Having one big website also adds a single point of failure and a new big infrastructure thing to maintain. I'm more fond of the distributed approach of small translation modules that users can install. That said, those translation modules could have pkgdown websites to host their documentation and sites like rdocumentation could also scrape and display that documentation (although, again, I'm not a fan on those websites; especially when they more prominent in search results than the actual package website). 

But, as I said, this project will create tools for translating .Rd files, so that could be used by anyone wanting to create what you propose. 

That said, the outputs of this proposal coudl be

**Comment by pedropark99** [comment]
Very fair point
> Having one big website also adds a single point of failure and a new big infrastructure thing to maintain. I'm more fond of the distributed approach of small translation modules that users can install.

I am not sure if my sugestion is really a good move, I just anotatted it down, before I forgot them 😅. I might also have read too fast your proposal, and not fully understood what you are thinking. Anyway, I still think this is a very interesting proposal you have.

**Comment by eliocamp** [comment]
Thanks! And thank you for the message. One thing to note is that nothing is set in stone, because this is all very experimental and the point of implementing this as a packages is precisely being able to test stuff and prototype without needing the R sourcecode "keys", so alternative suggestions are always welcomed.
